// Real photos from Doston (24.09.2026). Captions are written by us from what the photos show;
// years are approximate (after the registration date 29.10.2018), as the owner instructed.
window.WORKS = [
  { img: 74763, more: [74788, 74784], year: 2023,
    t: { uz: "Ташкилот учун банкет-фуршет", ru: "Банкет-фуршет для организации", en: "Banquet buffet for an organization" },
    o: { uz: "Корпоратив тадбир", ru: "Корпоративное мероприятие", en: "Corporate event" },
    d: { uz: "Совуқ газаклар, самса, пишириқлар, мевалар ва десертлар билан тўлиқ фуршет: безатиш, сервировка ва меҳмонларга хизмат кўрсатиш.",
         ru: "Полный фуршет: холодные закуски, самса, выпечка, фрукты и десерты. Оформление стола, сервировка и обслуживание гостей.",
         en: "A full buffet with cold starters, samsa, pastries, fruit and desserts, including table styling, serving and guest service." } },
  { img: 74800, more: [74796], year: 2022,
    t: { uz: "Катта овқатланиш залида байрам тушлиги", ru: "Праздничный обед в большом обеденном зале", en: "Festive lunch in a large dining hall" },
    o: { uz: "Мудофаа вазирлиги тизимидаги ташкилот", ru: "Организация системы Министерства обороны", en: "Organization within the Ministry of Defense system" },
    d: { uz: "Юзлаб ўринли залда ҳар бир стол бир хил тартибда тайёрланди: иссиқ таом, салатлар, мевалар, ичимликлар ва чой.",
         ru: "Зал на сотни мест: каждый стол накрыт одинаково. Горячее, салаты, фрукты, напитки и чай.",
         en: "A hall with hundreds of seats, every table set the same way: hot meals, salads, fruit, drinks and tea." } },
  { img: 74841, more: [74846], year: 2024,
    t: { uz: "Спорт мактаби тарбияланувчилари учун кунлик овқат", ru: "Ежедневное питание воспитанников спортивной школы", en: "Daily meals for sports school students" },
    o: { uz: "Спорт мактаби", ru: "Спортивная школа", en: "Sports school" },
    d: { uz: "Спортчилар учун тўйимли ва мувозанатли таомлар: шўрва, иккинчи таом, салат, нон, сут маҳсулотлари ва мевалар.",
         ru: "Сытное сбалансированное меню для спортсменов: суп, второе блюдо, салат, хлеб, молочные продукты и фрукты.",
         en: "Nourishing, balanced meals for young athletes: soup, a main course, salad, bread, dairy and fruit." } },
  { img: 74838, more: [74839, 74840], year: 2021,
    t: { uz: "Тарқатиш линиясида комплекс тушликлар", ru: "Комплексные обеды на линии раздачи", en: "Set lunches on the serving line" },
    o: { uz: "Ташкилот ошхонаси", ru: "Столовая организации", en: "Organization canteen" },
    d: { uz: "Ҳар куни янги тайёрланган бир нечта иссиқ таом ва гарнирлар, тез ва тартибли тарқатиш.",
         ru: "Каждый день несколько свежих горячих блюд и гарниров. Быстрая и аккуратная раздача.",
         en: "Several freshly cooked hot dishes and sides every day, served quickly and neatly." } },
  { img: 74778, more: [], year: 2019,
    t: { uz: "Очиқ ҳаводаги дала ошхонаси", ru: "Выездная полевая кухня", en: "Field kitchen outdoors" },
    o: { uz: "Очиқ ҳаводаги тадбир", ru: "Мероприятие на открытом воздухе", en: "Outdoor event" },
    d: { uz: "Дала шароитида таом тайёрлаш ва тарқатиш: кўчма ошхона, транспорт ва жамоа жойида ишлади.",
         ru: "Приготовление и раздача еды в полевых условиях: мобильная кухня, транспорт и команда на месте.",
         en: "Cooking and serving food in the field with a mobile kitchen, our own transport and an on-site team." } },
  { img: 74815, more: [74812], year: 2020,
    t: { uz: "Порцияли тушликлар", ru: "Порционные обеды", en: "Portioned lunches" },
    o: { uz: "Ташкилот ошхонаси", ru: "Столовая организации", en: "Organization canteen" },
    d: { uz: "Ҳар бир патнисда тўлиқ тушлик: биринчи ва иккинчи таом, салат ва нон. Порциялар бир хил ва гигиеник.",
         ru: "На каждом подносе полный обед: первое, второе, салат и хлеб. Одинаковые порции, соблюдение гигиены.",
         en: "A complete lunch on every tray: soup, a main course, salad and bread. Equal portions, hygienic serving." } },
  { img: 74855, more: [74864], year: 2025,
    t: { uz: "Сабзавот ва меваларни етказиб бериш", ru: "Поставка овощей и фруктов", en: "Vegetable and fruit supply" },
    o: { uz: "Ошхоналарни таъминлаш", ru: "Снабжение столовых", en: "Supplying canteens" },
    d: { uz: "Ўз транспортимизда ошхоналарга сабзавот, мева ва бошқа маҳсулотларни мунтазам етказиб берамиз.",
         ru: "Регулярно доставляем в столовые овощи, фрукты и другие продукты на собственном транспорте.",
         en: "Regular deliveries of vegetables, fruit and other products to canteens with our own vehicles." } },
  { img: 74866, more: [], year: 2025,
    t: { uz: "Янги гўшт етказиб бериш", ru: "Поставка свежего мяса", en: "Fresh meat supply" },
    o: { uz: "Ошхоналарни таъминлаш", ru: "Снабжение столовых", en: "Supplying canteens" },
    d: { uz: "Гўшт совутгичли транспортда ташилади, сақлаш шароитига риоя қилинади.",
         ru: "Мясо перевозится в рефрижераторе с соблюдением условий хранения.",
         en: "Meat is transported in a refrigerated vehicle under proper storage conditions." } },
  { img: 74825, more: [], year: 2023,
    t: { uz: "Байрам столи сервировкаси", ru: "Праздничная сервировка стола", en: "Festive table setting" },
    o: { uz: "Расмий қабул", ru: "Официальный приём", en: "Official reception" },
    d: { uz: "Оқ дастурхон, чиройли идишлар, салатлар ва мевалар: расмий тадбир учун тўлиқ тайёрланган стол.",
         ru: "Белые скатерти, красивая посуда, салаты и фрукты: стол, полностью подготовленный к официальному приёму.",
         en: "White tablecloths, fine tableware, salads and fruit: a table fully prepared for an official reception." } },
  { img: 74814, more: [], year: 2022,
    t: { uz: "Мангалда кабоб", ru: "Шашлык на мангале", en: "Grilled kebabs" },
    o: { uz: "Байрам тадбири", ru: "Праздничное мероприятие", en: "Celebration" },
    d: { uz: "Меҳмонлар олдида тайёрланадиган иссиқ кабоб: гўшт, кўмир ва тажрибали ошпаз.",
         ru: "Шашлык, который готовят прямо при гостях: мясо, угли и опытный повар.",
         en: "Kebabs grilled right in front of the guests by an experienced cook." } },
  { img: 74826, more: [74828], year: 2021,
    t: { uz: "Ошхонадаги иш", ru: "Работа кухни", en: "Our kitchen at work" },
    o: { uz: "Ишлаб чиқариш ошхонаси", ru: "Производственная кухня", en: "Production kitchen" },
    d: { uz: "Катта қозонлар ва профессионал ускуналар: юзлаб порцияни бир вақтда тайёрлаймиз.",
         ru: "Большие котлы и профессиональное оборудование: готовим сотни порций одновременно.",
         en: "Large kettles and professional equipment let us cook hundreds of portions at once." } },
  { img: 74785, more: [74786], year: 2024,
    t: { uz: "Фуршет учун десертлар", ru: "Десерты для фуршета", en: "Desserts for a buffet" },
    o: { uz: "Корпоратив тадбир", ru: "Корпоративное мероприятие", en: "Corporate event" },
    d: { uz: "Пирожнийлар, кексолар ва мевали композициялар: фуршетнинг ширин якуни.",
         ru: "Пирожные, кексы и фруктовые композиции: сладкое завершение фуршета.",
         en: "Pastries, cupcakes and fruit arrangements: a sweet finish to the buffet." } }
];

window.TEAM_PHOTOS = [74824, 74821, 74854, 74830, 74766];
